export type AssistantId =
  | 'claude'
  | 'copilot'
  | 'cursor'
  | 'aider'
  | 'cline'
  | 'codeium'
  | 'devin'
  | 'sweep'
  | 'continue'
  | 'generic';

export type MarkerDefinition = {
  readonly assistant: AssistantId;
  readonly label: string;
  readonly accent: string;
  // Single canonical query used to count commits via /search/commits.
  // Picked so a typical commit from this assistant matches once and only once
  // — e.g. Claude Code commits include both `Co-Authored-By: Claude` and
  // `noreply@anthropic.com` in the trailer, so we count by the most specific
  // marker (the trailer) and don't double-count via the email.
  readonly primaryQuery: string;
  // Patterns used to identify the assistant from a commit message body when
  // labelling samples and detecting "patient zero".
  readonly patterns: readonly RegExp[];
};

export const markers: readonly MarkerDefinition[] = [
  {
    assistant: 'claude',
    label: 'Claude Code',
    accent: '#c89bff',
    primaryQuery: '"Co-Authored-By: Claude"',
    patterns: [
      /Co-?Authored-?By:\s*Claude/i,
      /Generated with \[?Claude Code\]?/i,
      /noreply@anthropic\.com/i,
      /🤖\s*Generated with/i,
    ],
  },
  {
    assistant: 'copilot',
    label: 'GitHub Copilot',
    accent: '#5a8cff',
    primaryQuery: '"Co-Authored-By: copilot"',
    patterns: [/Co-?Authored-?By:\s*(github\s+)?copilot/i, /\bgh\s+copilot\b/i],
  },
  {
    assistant: 'cursor',
    label: 'Cursor',
    accent: '#3fd9a3',
    primaryQuery: '"Co-Authored-By: Cursor"',
    patterns: [/Co-?Authored-?By:\s*Cursor/i, /Generated by Cursor/i, /\[Cursor]/i],
  },
  {
    assistant: 'aider',
    label: 'Aider',
    accent: '#f5c66b',
    primaryQuery: '"aider:"',
    patterns: [/^aider:/im, /Co-?Authored-?By:\s*aider/i],
  },
  {
    assistant: 'cline',
    label: 'Cline',
    accent: '#ff8a4c',
    primaryQuery: '"Co-Authored-By: Cline"',
    patterns: [/Co-?Authored-?By:\s*Cline/i, /Generated by Cline/i],
  },
  {
    assistant: 'codeium',
    label: 'Codeium / Windsurf',
    accent: '#7df0e9',
    primaryQuery: '"Co-Authored-By: Codeium"',
    patterns: [/Co-?Authored-?By:\s*(Codeium|Windsurf)/i, /Generated by Windsurf/i],
  },
  {
    assistant: 'devin',
    label: 'Devin',
    accent: '#b39bff',
    primaryQuery: '"Co-Authored-By: Devin"',
    patterns: [/Co-?Authored-?By:\s*Devin/i, /Generated by Devin/i],
  },
  {
    assistant: 'sweep',
    label: 'Sweep AI',
    accent: '#ff6b81',
    primaryQuery: '"Co-Authored-By: sweep"',
    patterns: [/Co-?Authored-?By:\s*sweep/i],
  },
  {
    assistant: 'continue',
    label: 'Continue.dev',
    accent: '#9aa7c7',
    primaryQuery: '"Generated by Continue"',
    patterns: [/Generated by Continue\b/i],
  },
] as const;

export const markersByAssistant: ReadonlyMap<AssistantId, MarkerDefinition> = new Map(
  markers.map((m) => [m.assistant, m]),
);

export function detectAssistant(message: string): AssistantId | null {
  for (const marker of markers) {
    if (marker.patterns.some((p) => p.test(message))) return marker.assistant;
  }
  return null;
}
