export type AssistantId =
  | 'claude'
  | 'copilot'
  | 'cursor'
  | 'codex'
  | 'aider'
  | 'cline'
  | 'codeium'
  | 'devin'
  | 'sweep'
  | 'continue'
  | 'gpt-engineer'
  | 'tabnine'
  | 'generic';

export type MarkerDefinition = {
  readonly assistant: AssistantId;
  readonly label: string;
  readonly accent: string;
  // Search-API terms unioned with OR into a single query so GitHub dedupes
  // matching commits internally — total_count is unique-by-SHA per assistant.
  // Cast as wide a net as possible without bleeding into other assistants.
  readonly queryTerms: readonly string[];
  // Patterns used to identify the assistant from a commit message body when
  // labelling samples and detecting "patient zero".
  readonly patterns: readonly RegExp[];
};

export const markers: readonly MarkerDefinition[] = [
  {
    assistant: 'claude',
    label: 'Claude Code',
    accent: '#c89bff',
    queryTerms: [
      '"Co-Authored-By: Claude"',
      '"Generated with Claude Code"',
      '"noreply@anthropic.com"',
      '"🤖 Generated with"',
    ],
    patterns: [
      /Co-?Authored-?By:\s*Claude/i,
      /Generated with \[?Claude Code\]?/i,
      /noreply@anthropic\.com/i,
      /🤖\s*Generated with/i,
    ],
  },
  {
    assistant: 'copilot',
    label: 'GitHub Copilot',
    accent: '#5a8cff',
    queryTerms: [
      '"Co-Authored-By: copilot"',
      '"Co-Authored-By: GitHub Copilot"',
      '"copilot-swe-agent"',
      '"copilot@github.com"',
    ],
    patterns: [
      /Co-?Authored-?By:\s*(github\s+)?copilot/i,
      /copilot-swe-agent/i,
      /copilot@github\.com/i,
      /\bgh\s+copilot\b/i,
    ],
  },
  {
    assistant: 'cursor',
    label: 'Cursor',
    accent: '#3fd9a3',
    queryTerms: ['"Co-Authored-By: Cursor"', '"Generated by Cursor"', '"cursor-agent"'],
    patterns: [
      /Co-?Authored-?By:\s*Cursor/i,
      /Generated by Cursor/i,
      /\[Cursor]/i,
      /cursor-agent/i,
    ],
  },
  {
    assistant: 'codex',
    label: 'OpenAI Codex',
    accent: '#10a37f',
    queryTerms: [
      '"Co-Authored-By: openai-codex"',
      '"Co-Authored-By: codex"',
      '"Co-Authored-By: ChatGPT"',
      '"chatgpt-codex-connector"',
      '"codex@openai.com"',
      '"Generated by Codex"',
      '"Generated with OpenAI Codex"',
    ],
    patterns: [
      /Co-?Authored-?By:\s*(openai-)?codex/i,
      /Co-?Authored-?By:\s*ChatGPT/i,
      /chatgpt-codex-connector/i,
      /codex@openai\.com/i,
      /Generated (by|with) (OpenAI )?Codex/i,
    ],
  },
  {
    assistant: 'aider',
    label: 'Aider',
    accent: '#f5c66b',
    queryTerms: ['"aider:"', '"Co-Authored-By: aider"', '"aider-ai"'],
    patterns: [/^aider:/im, /Co-?Authored-?By:\s*aider/i, /aider-ai/i],
  },
  {
    assistant: 'cline',
    label: 'Cline',
    accent: '#ff8a4c',
    queryTerms: ['"Co-Authored-By: Cline"', '"Generated by Cline"'],
    patterns: [/Co-?Authored-?By:\s*Cline/i, /Generated by Cline/i],
  },
  {
    assistant: 'codeium',
    label: 'Codeium / Windsurf',
    accent: '#7df0e9',
    queryTerms: [
      '"Co-Authored-By: Codeium"',
      '"Co-Authored-By: Windsurf"',
      '"Generated by Windsurf"',
    ],
    patterns: [/Co-?Authored-?By:\s*(Codeium|Windsurf)/i, /Generated by Windsurf/i],
  },
  {
    assistant: 'devin',
    label: 'Devin',
    accent: '#b39bff',
    queryTerms: ['"Co-Authored-By: Devin"', '"Generated by Devin"', '"devin-ai-integration"'],
    patterns: [/Co-?Authored-?By:\s*Devin/i, /Generated by Devin/i, /devin-ai-integration/i],
  },
  {
    assistant: 'sweep',
    label: 'Sweep AI',
    accent: '#ff6b81',
    queryTerms: ['"Co-Authored-By: sweep"', '"sweep-ai"'],
    patterns: [/Co-?Authored-?By:\s*sweep/i, /sweep-ai/i],
  },
  {
    assistant: 'continue',
    label: 'Continue.dev',
    accent: '#9aa7c7',
    queryTerms: ['"Generated by Continue"', '"Co-Authored-By: continue"'],
    patterns: [/Generated by Continue\b/i, /Co-?Authored-?By:\s*continue/i],
  },
  {
    assistant: 'gpt-engineer',
    label: 'GPT Engineer',
    accent: '#9bf0c8',
    queryTerms: ['"Co-Authored-By: gpt-engineer"', '"Generated by gpt-engineer"'],
    patterns: [/Co-?Authored-?By:\s*gpt-engineer/i, /Generated by gpt-engineer/i],
  },
  {
    assistant: 'tabnine',
    label: 'Tabnine',
    accent: '#ffb05c',
    queryTerms: ['"Co-Authored-By: Tabnine"', '"Generated by Tabnine"'],
    patterns: [/Co-?Authored-?By:\s*Tabnine/i, /Generated by Tabnine/i],
  },
] as const;

export const markersByAssistant: ReadonlyMap<AssistantId, MarkerDefinition> = new Map(
  markers.map((m) => [m.assistant, m]),
);

export function detectAssistant(message: string): AssistantId | null {
  for (const marker of markers) {
    if (marker.patterns.some((p) => p.test(message))) return marker.assistant;
  }
  return null;
}

// Build a single GitHub /search/commits query that ORs all of an assistant's
// canonical signatures together. GitHub returns total_count deduplicated by
// SHA, so we get an accurate per-assistant count in one API call regardless
// of how many overlapping marker variants we list.
export function buildAssistantQuery(marker: MarkerDefinition): string {
  if (marker.queryTerms.length === 1) return marker.queryTerms[0]!;
  return `(${marker.queryTerms.join(' OR ')})`;
}
