import { describe, expect, test } from 'bun:test';
import {
  buildAssistantQuery,
  detectAssistant,
  markers,
  markersByAssistant,
} from '~/domain/markers';

describe('markers catalog', () => {
  test('every marker has at least one query term and one pattern', () => {
    for (const marker of markers) {
      expect(marker.queryTerms.length).toBeGreaterThan(0);
      expect(marker.patterns.length).toBeGreaterThan(0);
    }
  });

  test('query terms are distinct within each assistant', () => {
    for (const marker of markers) {
      const seen = new Set<string>();
      for (const term of marker.queryTerms) {
        expect(seen.has(term)).toBe(false);
        seen.add(term);
      }
    }
  });

  test('buildAssistantQuery wraps multi-term markers in parens with OR', () => {
    const claude = markersByAssistant.get('claude');
    expect(claude).toBeDefined();
    const query = buildAssistantQuery(claude!);
    expect(query.startsWith('(')).toBe(true);
    expect(query.endsWith(')')).toBe(true);
    expect(query.includes(' OR ')).toBe(true);
  });

  test('buildAssistantQuery does not wrap single-term markers', () => {
    const single = markers.find((m) => m.queryTerms.length === 1);
    if (!single) return;
    const query = buildAssistantQuery(single);
    expect(query).toBe(single.queryTerms[0]!);
  });

  test('markersByAssistant indexes every entry', () => {
    expect(markersByAssistant.size).toBe(markers.length);
    for (const marker of markers) {
      expect(markersByAssistant.get(marker.assistant)?.label).toBe(marker.label);
    }
  });

  test('every marker accent is a hex color', () => {
    for (const marker of markers) {
      expect(marker.accent).toMatch(/^#[0-9a-f]{6}$/i);
    }
  });
});

describe('detectAssistant', () => {
  test('detects Claude Code trailers', () => {
    expect(detectAssistant('feat: add foo\n\nCo-Authored-By: Claude <noreply@anthropic.com>')).toBe(
      'claude',
    );
    expect(detectAssistant('🤖 Generated with Claude Code')).toBe('claude');
  });

  test('detects Copilot', () => {
    expect(detectAssistant('Co-Authored-By: GitHub Copilot <bot@github.com>')).toBe('copilot');
    expect(detectAssistant('Co-Authored-By: copilot')).toBe('copilot');
  });

  test('detects Cursor', () => {
    expect(detectAssistant('feat: refactor\n\nGenerated by Cursor')).toBe('cursor');
    expect(detectAssistant('[Cursor] tweak settings')).toBe('cursor');
  });

  test('detects Aider when message starts with the trailer', () => {
    expect(detectAssistant('aider: change the cli flag handling')).toBe('aider');
  });

  test('detects Cline / Windsurf / Devin / Sweep / GPT Engineer / Tabnine', () => {
    expect(detectAssistant('Co-Authored-By: Cline <cline@cline.bot>')).toBe('cline');
    expect(detectAssistant('Generated by Windsurf')).toBe('codeium');
    expect(detectAssistant('Co-Authored-By: Devin <devin@cognition.com>')).toBe('devin');
    expect(detectAssistant('Co-Authored-By: sweep <sweep@sweep.dev>')).toBe('sweep');
    expect(detectAssistant('Co-Authored-By: gpt-engineer <bot@example.com>')).toBe('gpt-engineer');
    expect(detectAssistant('Co-Authored-By: Tabnine <tabnine@tabnine.com>')).toBe('tabnine');
  });

  test('detects bot-account email signatures (the wider trap)', () => {
    expect(detectAssistant('chore: bump deps\n\nfrom: copilot@github.com')).toBe('copilot');
    expect(detectAssistant('feat: thing\n\ncopilot-swe-agent ran the test suite')).toBe('copilot');
    expect(detectAssistant('build: rebase\n\ncursor-agent applied the patch')).toBe('cursor');
    expect(detectAssistant('feat: setup\n\ndevin-ai-integration\nbot signoff')).toBe('devin');
  });

  test('returns null for messages without any AI marker', () => {
    expect(detectAssistant('chore: bump dependency versions')).toBeNull();
    expect(detectAssistant('Merge pull request #42 from feature/branch')).toBeNull();
  });

  test('is case-insensitive on the canonical trailer keys', () => {
    expect(detectAssistant('co-authored-by: claude <noreply@anthropic.com>')).toBe('claude');
    expect(detectAssistant('CO-AUTHORED-BY: GITHUB COPILOT')).toBe('copilot');
  });
});
