import { describe, expect, test } from 'bun:test';
import { detectAssistant, markers, markersByAssistant } from '~/domain/markers';

describe('markers catalog', () => {
  test('every marker has a primary query and at least one pattern', () => {
    for (const marker of markers) {
      expect(marker.primaryQuery.length).toBeGreaterThan(0);
      expect(marker.patterns.length).toBeGreaterThan(0);
    }
  });

  test('primary queries are distinct (so /search/commits totals do not overlap)', () => {
    const seen = new Set<string>();
    for (const marker of markers) {
      expect(seen.has(marker.primaryQuery)).toBe(false);
      seen.add(marker.primaryQuery);
    }
  });

  test('markersByAssistant indexes every entry', () => {
    expect(markersByAssistant.size).toBe(markers.length);
    for (const marker of markers) {
      expect(markersByAssistant.get(marker.assistant)?.label).toBe(marker.label);
    }
  });

  test('every marker accent is a hex color', () => {
    for (const marker of markers) {
      expect(marker.accent).toMatch(/^#[0-9a-f]{6}$/i);
    }
  });
});

describe('detectAssistant', () => {
  test('detects Claude Code trailers', () => {
    expect(detectAssistant('feat: add foo\n\nCo-Authored-By: Claude <noreply@anthropic.com>')).toBe(
      'claude',
    );
    expect(detectAssistant('🤖 Generated with Claude Code')).toBe('claude');
  });

  test('detects Copilot', () => {
    expect(detectAssistant('Co-Authored-By: GitHub Copilot <bot@github.com>')).toBe('copilot');
    expect(detectAssistant('Co-Authored-By: copilot')).toBe('copilot');
  });

  test('detects Cursor', () => {
    expect(detectAssistant('feat: refactor\n\nGenerated by Cursor')).toBe('cursor');
    expect(detectAssistant('[Cursor] tweak settings')).toBe('cursor');
  });

  test('detects Aider when message starts with the trailer', () => {
    expect(detectAssistant('aider: change the cli flag handling')).toBe('aider');
  });

  test('detects Cline / Windsurf / Devin / Sweep', () => {
    expect(detectAssistant('Co-Authored-By: Cline <cline@cline.bot>')).toBe('cline');
    expect(detectAssistant('Generated by Windsurf')).toBe('codeium');
    expect(detectAssistant('Co-Authored-By: Devin <devin@cognition.com>')).toBe('devin');
    expect(detectAssistant('Co-Authored-By: sweep <sweep@sweep.dev>')).toBe('sweep');
  });

  test('returns null for messages without any AI marker', () => {
    expect(detectAssistant('chore: bump dependency versions')).toBeNull();
    expect(detectAssistant('Merge pull request #42 from feature/branch')).toBeNull();
  });

  test('is case-insensitive on the canonical trailer keys', () => {
    expect(detectAssistant('co-authored-by: claude <noreply@anthropic.com>')).toBe('claude');
    expect(detectAssistant('CO-AUTHORED-BY: GITHUB COPILOT')).toBe('copilot');
  });
});
