export type AssistantId =
  | 'claude'
  | 'copilot'
  | 'cursor'
  | 'aider'
  | 'cline'
  | 'codeium'
  | 'devin'
  | 'sweep'
  | 'continue'
  | 'generic';

export type MarkerDefinition = {
  readonly assistant: AssistantId;
  readonly label: string;
  readonly accent: string;
  readonly queries: readonly string[];
  readonly patterns: readonly RegExp[];
};

export const markers: readonly MarkerDefinition[] = [
  {
    assistant: 'claude',
    label: 'Claude Code',
    accent: '#c89bff',
    queries: [
      '"Co-Authored-By: Claude"',
      '"Generated with Claude Code"',
      '"noreply@anthropic.com"',
    ],
    patterns: [
      /Co-?Authored-?By:\s*Claude/i,
      /Generated with \[?Claude Code\]?/i,
      /noreply@anthropic\.com/i,
      /🤖\s*Generated with/i,
    ],
  },
  {
    assistant: 'copilot',
    label: 'GitHub Copilot',
    accent: '#5a8cff',
    queries: ['"Co-Authored-By: copilot"', '"Co-Authored-By: GitHub Copilot"'],
    patterns: [/Co-?Authored-?By:\s*(github\s+)?copilot/i, /\bgh\s+copilot\b/i],
  },
  {
    assistant: 'cursor',
    label: 'Cursor',
    accent: '#3fd9a3',
    queries: ['"Co-Authored-By: Cursor"', '"Generated by Cursor"'],
    patterns: [/Co-?Authored-?By:\s*Cursor/i, /Generated by Cursor/i, /\[Cursor]/i],
  },
  {
    assistant: 'aider',
    label: 'Aider',
    accent: '#f5c66b',
    queries: ['"aider:"', '"Co-Authored-By: aider"'],
    patterns: [/^aider:/im, /Co-?Authored-?By:\s*aider/i],
  },
  {
    assistant: 'cline',
    label: 'Cline',
    accent: '#ff8a4c',
    queries: ['"Co-Authored-By: Cline"', '"Generated by Cline"'],
    patterns: [/Co-?Authored-?By:\s*Cline/i, /Generated by Cline/i],
  },
  {
    assistant: 'codeium',
    label: 'Codeium / Windsurf',
    accent: '#7df0e9',
    queries: ['"Co-Authored-By: Codeium"', '"Generated by Windsurf"'],
    patterns: [/Co-?Authored-?By:\s*(Codeium|Windsurf)/i, /Generated by Windsurf/i],
  },
  {
    assistant: 'devin',
    label: 'Devin',
    accent: '#b39bff',
    queries: ['"Co-Authored-By: Devin"', '"Generated by Devin"'],
    patterns: [/Co-?Authored-?By:\s*Devin/i, /Generated by Devin/i],
  },
  {
    assistant: 'sweep',
    label: 'Sweep AI',
    accent: '#ff6b81',
    queries: ['"Co-Authored-By: sweep"'],
    patterns: [/Co-?Authored-?By:\s*sweep/i],
  },
  {
    assistant: 'continue',
    label: 'Continue.dev',
    accent: '#9aa7c7',
    queries: ['"Generated by Continue"'],
    patterns: [/Generated by Continue\b/i],
  },
] as const;

export const markersByAssistant: ReadonlyMap<AssistantId, MarkerDefinition> = new Map(
  markers.map((m) => [m.assistant, m]),
);

export function detectAssistant(message: string): AssistantId | null {
  for (const marker of markers) {
    if (marker.patterns.some((p) => p.test(message))) return marker.assistant;
  }
  return null;
}
