import { useEffect } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router';
import { AppShell } from '~/components/layout/AppShell';
import { Badge } from '~/components/ui/Badge';
import { useSession } from '~/hooks/useSession';
import { loginWithGitHub } from '~/lib/appwrite';

const features = [
  {
    title: 'Patient zero',
    body: 'We pinpoint the exact commit where AI first joined your workflow — Claude Code, Copilot, Cursor, Codex, Aider, Cline, Windsurf, and more.',
  },
  {
    title: 'The multiplier',
    body: 'Mean monthly commits before that marker, mean after. One number, rounded to a single decimal. Honest, hard to fake.',
  },
  {
    title: 'Field signals',
    body: 'Assistant mix, AI commit share, longest streak, peak hour and weekday in your local time, and a dev-days-saved estimate.',
  },
];

const markers = [
  ['Claude Code', 'Co-Authored-By: Claude'],
  ['GitHub Copilot', 'Co-Authored-By: copilot'],
  ['Cursor', 'Generated by Cursor'],
  ['OpenAI Codex', 'codex@openai.com'],
  ['Aider', 'aider:'],
  ['Windsurf', 'Co-Authored-By: Windsurf'],
  ['Devin', 'devin-ai-integration'],
  ['Cline', 'Co-Authored-By: Cline'],
] as const;

export function LandingPage() {
  const session = useSession();
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const authFailed = params.get('auth') === 'failed';

  useEffect(() => {
    if (session.data) navigate('/dashboard', { replace: true });
  }, [session.data, navigate]);

  return (
    <AppShell>
      <section className="mx-auto max-w-[1240px] px-6 pt-20 pb-24">
        <div className="grid grid-cols-12 gap-8 items-start">
          <div className="col-span-12 lg:col-span-7 flex flex-col gap-7">
            <Badge tone="accent" dot>
              v1 · open beta
            </Badge>
            <h1 className="text-[clamp(44px,7vw,80px)] font-semibold leading-[1.02] tracking-[-0.035em] text-[var(--color-text-strong)]">
              How much faster has AI made you?
            </h1>
            <p className="text-[18px] leading-[1.55] text-[var(--color-text)] max-w-[55ch]">
              Sign in with GitHub. We find your first AI-assisted commit, then compute the
              multiplier on every month of output that came after. Read-only — your token never
              leaves the browser.
            </p>
            <div className="flex flex-wrap items-center gap-3 pt-1">
              <button
                type="button"
                onClick={loginWithGitHub}
                className="group inline-flex items-center gap-2.5 pl-4 pr-5 h-11 bg-[var(--color-accent)] hover:bg-[var(--color-accent-hover)] text-white rounded-[var(--radius-md)] transition-colors font-medium text-[14px] shadow-[inset_0_1px_0_0_rgba(255,255,255,0.16)]"
              >
                <GitHubMark />
                <span>Continue with GitHub</span>
                <span className="text-[16px] -mr-0.5 transition-transform group-hover:translate-x-0.5">
                  →
                </span>
              </button>
              <Link
                to="/dashboard?demo=ready"
                className="inline-flex items-center h-11 px-4 text-[14px] text-[var(--color-text-strong)] hover:bg-[var(--color-surface)] border border-[var(--color-border)] hover:border-[var(--color-border-strong)] rounded-[var(--radius-md)] transition-colors"
              >
                See a sample
              </Link>
            </div>
            <p className="text-[12px] text-[var(--color-muted)]">
              Read-only · GitHub App · no source is read · token stays local
            </p>
            {authFailed && (
              <div className="flex items-center gap-3 px-3 py-2.5 rounded-[var(--radius-md)] border border-[color-mix(in_oklab,var(--color-danger)_45%,transparent)] bg-[color-mix(in_oklab,var(--color-danger)_8%,transparent)]">
                <span className="size-1.5 rounded-full bg-[var(--color-danger)]" />
                <span className="text-[13px] text-[var(--color-text-strong)]">
                  Authentication failed.
                </span>
                <span className="text-[13px] text-[var(--color-muted-2)]">
                  Try again or check the GitHub provider settings.
                </span>
              </div>
            )}
          </div>

          <div className="col-span-12 lg:col-span-5">
            <SamplePreview />
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-[1240px] px-6 pb-24">
        <SectionHead
          eyebrow="What it measures"
          title="Three numbers that matter."
          description="Designed to be skimmable in five seconds and defensible in five minutes."
        />
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-8">
          {features.map((feature, i) => (
            <article
              key={feature.title}
              className="surface edge-light p-6 flex flex-col gap-3 hover:border-[var(--color-border-strong)] transition-colors"
            >
              <span className="text-[12px] tabular-nums text-[var(--color-muted)] font-mono">
                {String(i + 1).padStart(2, '0')}
              </span>
              <h3 className="text-[15px] font-semibold text-[var(--color-text-strong)] tracking-tight">
                {feature.title}
              </h3>
              <p className="text-[13px] text-[var(--color-muted-2)] leading-relaxed">
                {feature.body}
              </p>
            </article>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-[1240px] px-6 pb-24">
        <SectionHead
          eyebrow="Detection"
          title="Signatures we look for."
          description="Canonical co-author trailers and bot signatures left behind by each assistant."
        />
        <div className="grid grid-cols-12 gap-6 mt-8">
          <div className="col-span-12 md:col-span-4">
            <p className="text-[14px] leading-[1.65] text-[var(--color-muted-2)]">
              The catalog is{' '}
              <a
                href="https://github.com/abnegate/your-ai-boost/blob/main/src/domain/markers.ts"
                className="text-[var(--color-accent)] hover:text-[var(--color-accent-hover)] underline underline-offset-4 decoration-[color-mix(in_oklab,var(--color-accent)_40%,transparent)]"
              >
                open and tested
              </a>
              . Suggestions welcome.
            </p>
          </div>
          <ul className="col-span-12 md:col-span-8 grid grid-cols-1 sm:grid-cols-2 gap-2">
            {markers.map(([name, sig]) => (
              <li
                key={name}
                className="flex items-center justify-between gap-3 px-3.5 py-2.5 rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-surface)] hover:border-[var(--color-border-strong)] transition-colors"
              >
                <span className="text-[13px] text-[var(--color-text-strong)] truncate">{name}</span>
                <code className="text-[11px] text-[var(--color-muted)] font-mono truncate">
                  {sig}
                </code>
              </li>
            ))}
          </ul>
        </div>
      </section>
    </AppShell>
  );
}

function SectionHead({
  eyebrow,
  title,
  description,
}: {
  readonly eyebrow: string;
  readonly title: string;
  readonly description: string;
}) {
  return (
    <div className="flex flex-col gap-2 max-w-[60ch]">
      <span className="text-[12px] font-medium text-[var(--color-accent)] tracking-tight">
        {eyebrow}
      </span>
      <h2 className="text-[28px] font-semibold tracking-[-0.025em] text-[var(--color-text-strong)] leading-tight">
        {title}
      </h2>
      <p className="text-[14px] text-[var(--color-muted-2)] leading-relaxed">{description}</p>
    </div>
  );
}

function SamplePreview() {
  return (
    <div className="surface edge-light p-6 ambient">
      <div className="flex items-center justify-between mb-4">
        <span className="text-[12px] font-medium text-[var(--color-muted-2)]">Sample output</span>
        <Badge tone="neutral">demo</Badge>
      </div>
      <div className="flex items-end gap-1 mb-4">
        <span className="text-[96px] leading-[0.85] font-semibold tracking-[-0.05em] text-[var(--color-text-strong)] tabular-nums">
          3.4
        </span>
        <span className="text-[64px] leading-[0.85] font-semibold tracking-[-0.05em] text-[var(--color-accent)] tabular-nums">
          ×
        </span>
      </div>
      <div className="grid grid-cols-2 gap-3 pt-4 border-t border-[var(--color-divider)]">
        <div className="flex flex-col gap-1">
          <span className="text-[11px] text-[var(--color-muted)]">Pre-AI</span>
          <span className="text-[16px] tabular-nums text-[var(--color-text)]">
            22 <span className="text-[12px] text-[var(--color-muted)]">/ mo</span>
          </span>
        </div>
        <div className="flex flex-col gap-1">
          <span className="text-[11px] text-[var(--color-muted)]">Post-AI</span>
          <span className="text-[16px] tabular-nums text-[var(--color-accent-hover)]">
            75 <span className="text-[12px] text-[var(--color-muted)]">/ mo</span>
          </span>
        </div>
      </div>
    </div>
  );
}

function GitHubMark() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden>
      <path d="M12 .3a12 12 0 0 0-3.8 23.4c.6.1.8-.3.8-.6v-2.3c-3.3.7-4-1.4-4-1.4-.6-1.4-1.4-1.8-1.4-1.8-1.1-.7.1-.7.1-.7 1.2.1 1.9 1.3 1.9 1.3 1.1 1.9 2.9 1.4 3.6 1.1.1-.8.4-1.4.8-1.7-2.7-.3-5.5-1.3-5.5-6 0-1.3.5-2.4 1.3-3.2-.1-.3-.6-1.6.1-3.4 0 0 1-.3 3.3 1.2a11.5 11.5 0 0 1 6 0c2.3-1.5 3.3-1.2 3.3-1.2.7 1.8.2 3.1.1 3.4.8.8 1.3 1.9 1.3 3.2 0 4.7-2.8 5.7-5.5 6 .4.4.8 1.1.8 2.2v3.3c0 .3.2.7.8.6A12 12 0 0 0 12 .3" />
    </svg>
  );
}
