import { useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router';
import { AppShell } from '~/components/layout/AppShell';
import { useSession } from '~/hooks/useSession';
import { loginWithGitHub } from '~/lib/appwrite';

const features = [
  {
    n: '01',
    title: 'Patient zero',
    body: 'We trace the exact commit where AI first joined your workflow — Claude, Copilot, Cursor, Codex, Aider, Cline, Codeium, Devin, Sweep, Continue, GPT Engineer, Tabnine.',
  },
  {
    n: '02',
    title: 'The multiplier',
    body: 'Average monthly commits before the marker, average after. One number, rounded to one decimal. Set in italic Instrument Serif because the number is the headline.',
  },
  {
    n: '03',
    title: 'Field notes',
    body: 'Assistant mix, AI commit share, longest streak, peak hour and weekday in your local time, and a dev-days reclaimed estimate. Read it like a report.',
  },
];

const markers = [
  ['Claude Code', 'Co-Authored-By: Claude'],
  ['GitHub Copilot', 'Co-Authored-By: copilot'],
  ['Cursor', 'Generated by Cursor'],
  ['OpenAI Codex', 'codex@openai.com'],
  ['Aider', 'aider:'],
  ['Windsurf', 'Co-Authored-By: Windsurf'],
  ['Devin', 'devin-ai-integration'],
  ['Cline', 'Co-Authored-By: Cline'],
] as const;

export function LandingPage() {
  const session = useSession();
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const authFailed = params.get('auth') === 'failed';

  useEffect(() => {
    if (session.data) navigate('/dashboard', { replace: true });
  }, [session.data, navigate]);

  return (
    <AppShell>
      {/* Hero */}
      <section className="relative">
        <div className="mx-auto max-w-[1280px] px-6 pt-12 pb-20">
          {/* Title block — asymmetric */}
          <div className="grid grid-cols-12 gap-6 items-end pb-16 border-b border-[var(--color-rule)]">
            <div className="col-span-12 md:col-span-2 flex flex-col gap-1">
              <span className="font-mono text-[10px] tracking-[0.24em] uppercase text-[var(--color-accent)]">
                Vol. 1 · No. 1
              </span>
              <span className="font-mono text-[10px] tracking-[0.24em] uppercase text-[var(--color-muted)]">
                a measurement
              </span>
            </div>
            <h1 className="col-span-12 md:col-span-10 display text-[clamp(56px,10vw,140px)] italic leading-[0.92] tracking-[-0.025em] text-[var(--color-paper)]">
              How many{' '}
              <span className="text-[var(--color-accent)] not-italic font-mono text-[0.6em] align-middle">
                ×
              </span>{' '}
              faster <br />
              has A.I. made <em className="not-italic">you?</em>
            </h1>
          </div>

          {/* Sub-grid: dek + CTA + meta */}
          <div className="grid grid-cols-12 gap-6 pt-10">
            <div className="col-span-12 md:col-span-7">
              <p className="text-[19px] leading-[1.55] text-[var(--color-text)] max-w-[55ch]">
                Sign in with GitHub. We pinpoint the first AI-assisted commit in your history, then
                compute the multiplier on every month of output that came after. The number lives or
                dies by your contribution graph &mdash; receipts attached.
              </p>

              <div className="mt-8 flex flex-wrap items-center gap-4">
                <button
                  type="button"
                  onClick={loginWithGitHub}
                  className="group inline-flex items-center gap-3 pl-4 pr-5 h-12 bg-[var(--color-paper)] text-[var(--color-canvas)] rounded-[var(--radius-sm)] hover:bg-white transition-colors font-medium"
                >
                  <GitHubMark />
                  <span>Continue with GitHub</span>
                  <span className="font-mono text-[10px] tracking-[0.16em] uppercase text-[var(--color-muted)] group-hover:text-[var(--color-canvas)] transition-colors">
                    →
                  </span>
                </button>
                <span className="font-mono text-[10px] tracking-[0.18em] uppercase text-[var(--color-muted)]">
                  read-only · no code is read · token stays in browser
                </span>
              </div>

              {authFailed && (
                <div className="mt-6 flex items-baseline gap-3 border-l-2 border-[var(--color-danger)] pl-3">
                  <span className="font-mono text-[10px] tracking-[0.18em] uppercase text-[var(--color-danger)]">
                    err 401
                  </span>
                  <span className="text-sm text-[var(--color-text)]">
                    Authentication failed. Try again or check the GitHub provider settings.
                  </span>
                </div>
              )}
            </div>

            {/* Specimen — a sample of the headline number */}
            <div className="col-span-12 md:col-span-5 md:pl-6 md:border-l md:border-[var(--color-rule)] flex flex-col items-start md:items-end justify-between gap-3">
              <div className="font-mono text-[10px] tracking-[0.24em] uppercase text-[var(--color-muted)]">
                Specimen / sample output
              </div>
              <div className="display italic text-[120px] leading-[0.9] text-[var(--color-paper)] tracking-[-0.04em]">
                3.4×
              </div>
              <div className="font-mono text-[10px] tracking-[0.2em] uppercase text-[var(--color-muted)] tabular-nums max-w-[24ch] md:text-right">
                ↳ pre-AI 22 commits / mo
                <br />↳ post-AI 75 commits / mo
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Method */}
      <section className="mx-auto max-w-[1280px] px-6">
        <div className="section-rule">§ 01 — Method</div>
        <div className="grid grid-cols-12 gap-x-6 gap-y-10 pt-8 pb-16">
          {features.map((feature) => (
            <article key={feature.n} className="col-span-12 md:col-span-4 group">
              <div className="flex items-baseline gap-3 mb-3 pb-3 border-b border-[var(--color-border)]">
                <span className="display italic text-[28px] text-[var(--color-accent)] leading-none">
                  {feature.n}
                </span>
                <h3 className="font-mono text-[11px] tracking-[0.2em] uppercase text-[var(--color-paper)]">
                  {feature.title}
                </h3>
              </div>
              <p className="text-[15px] leading-[1.65] text-[var(--color-text)]">{feature.body}</p>
            </article>
          ))}
        </div>
      </section>

      {/* Markers we look for — laid out like a glossary */}
      <section className="mx-auto max-w-[1280px] px-6 pb-20">
        <div className="section-rule">§ 02 — Glossary of signatures</div>
        <div className="grid grid-cols-12 gap-x-6 gap-y-2 pt-8">
          <p className="col-span-12 md:col-span-4 text-[15px] leading-[1.65] text-[var(--color-text)]">
            We scan commit messages for the canonical co-author trailers and bot signatures each
            assistant leaves behind. The catalog is{' '}
            <a
              href="https://github.com/abnegate/your-ai-boost/blob/main/src/domain/markers.ts"
              className="text-[var(--color-accent)] hover:underline"
            >
              open and tested
            </a>
            ; suggestions welcome.
          </p>
          <dl className="col-span-12 md:col-span-8 grid grid-cols-1 sm:grid-cols-2 gap-y-3 gap-x-8">
            {markers.map(([name, sig]) => (
              <div
                key={name}
                className="flex items-baseline gap-3 border-b border-dashed border-[var(--color-border)] pb-2"
              >
                <dt className="text-[14px] text-[var(--color-paper)] whitespace-nowrap">{name}</dt>
                <span className="flex-1 border-b border-dotted border-[var(--color-border)] mx-1 translate-y-[-3px]" />
                <dd className="font-mono text-[11px] text-[var(--color-muted)] whitespace-nowrap">
                  {sig}
                </dd>
              </div>
            ))}
          </dl>
        </div>
      </section>

      {/* Final masthead-ish strip */}
      <section className="mx-auto max-w-[1280px] px-6 pb-12">
        <div className="hatch h-[6px] mb-6" />
        <div className="flex flex-wrap items-baseline justify-between gap-4 font-mono text-[10px] tracking-[0.24em] uppercase text-[var(--color-muted)]">
          <span>End of issue ◆</span>
          <span>{new Date().toISOString().slice(0, 10)} · NZ&#8202;/&#8202;AKL</span>
          <span>Set in Instrument Serif</span>
        </div>
      </section>
    </AppShell>
  );
}

function GitHubMark() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden>
      <path d="M12 .3a12 12 0 0 0-3.8 23.4c.6.1.8-.3.8-.6v-2.3c-3.3.7-4-1.4-4-1.4-.6-1.4-1.4-1.8-1.4-1.8-1.1-.7.1-.7.1-.7 1.2.1 1.9 1.3 1.9 1.3 1.1 1.9 2.9 1.4 3.6 1.1.1-.8.4-1.4.8-1.7-2.7-.3-5.5-1.3-5.5-6 0-1.3.5-2.4 1.3-3.2-.1-.3-.6-1.6.1-3.4 0 0 1-.3 3.3 1.2a11.5 11.5 0 0 1 6 0c2.3-1.5 3.3-1.2 3.3-1.2.7 1.8.2 3.1.1 3.4.8.8 1.3 1.9 1.3 3.2 0 4.7-2.8 5.7-5.5 6 .4.4.8 1.1.8 2.2v3.3c0 .3.2.7.8.6A12 12 0 0 0 12 .3" />
    </svg>
  );
}
